# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

language: cpp

compiler:
  - clang

before_install:
  - cat /etc/apt/sources.list
  - ls -al /etc/apt/sources.list.d
  - sudo apt-get update -qq
#  - sudo apt-get install -y wine1.4-amd64
  - sudo apt-get install binutils-mingw-w64-i686
  - sudo apt-get install gcc-mingw-w64-i686
  - sudo apt-get install g++-mingw-w64-i686
  - sudo apt-get install g++-mingw-w64
#  - psql -c "drop database if exists autotest" -U postgres
#  - psql -c "create database autotest" -U postgres
#  - psql -c "create extension postgis" -d autotest -U postgres
#  - mysql -e "create database autotest;"
#  - mysql -e "GRANT ALL ON autotest.* TO 'root'@'localhost';" -u root
#  - mysql -e "GRANT ALL ON autotest.* TO 'travis'@'localhost';" -u root

install:
# build proj
  - curl http://download.osgeo.org/proj/proj-4.8.0.tar.gz > proj-4.8.0.tar.gz
  - tar xvzf proj-4.8.0.tar.gz
  - cd proj-4.8.0/nad
  - curl http://download.osgeo.org/proj/proj-datumgrid-1.5.tar.gz > proj-datumgrid-1.5.tar.gz
  - tar xvzf proj-datumgrid-1.5.tar.gz
  - cd ..
  - ./configure --host=x86_64-w64-mingw32
  - make -j3
  - cd ..
# build GDAL
  - cd gdal
  - ./configure --enable-debug --host=x86_64-w64-mingw32
  - make -j3
  - cd apps
  - make test_ogrsf.exe
  - cd ..
  - ln -s $PWD/.libs/libgdal-1.dll $HOME/.wine/drive_c/windows
  - ln -s /usr/lib/gcc/x86_64-w64-mingw32/4.6/libstdc++-6.dll  $HOME/.wine/drive_c/windows
  - ln -s /usr/lib/gcc/x86_64-w64-mingw32/4.6/libgcc_s_sjlj_1.dll  $HOME/.wine/drive_c/windows
  - ln -sf $PWD/../proj-4.8.0/src/.libs/libproj-0.dll $HOME/.wine/drive_c/windows

script:
  - wine64 apps/gdalinfo.exe --version

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true
    on_success: change
