# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

language: cpp

# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang

before_install:
  - export chroot="$PWD"/buildroot.i386
  - mkdir -p "$chroot$PWD"
  - sudo apt-get update
  - sudo apt-get install -y debootstrap
  - export LC_ALL=en_US
  - sudo i386 debootstrap --arch=i386 precise "$chroot"
  - sudo mount --rbind "$PWD" "$chroot$PWD"
  - sudo mount --rbind /dev/pts "$chroot/dev/pts"
  - sudo mount --rbind /proc "$chroot/proc"
  - sudo su -c 'echo "deb http://archive.ubuntu.com/ubuntu precise universe" >> buildroot.i386/etc/apt/sources.list'
  - sudo i386 chroot "$chroot" apt-get update
  - sudo i386 chroot "$chroot" apt-get install -y clang
  - sudo i386 chroot "$chroot" apt-get install -y python-software-properties
  - sudo i386 chroot "$chroot" add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo i386 chroot "$chroot" add-apt-repository -y ppa:marlam/gta
  - sudo i386 chroot "$chroot" apt-get update
  - sudo i386 chroot "$chroot" apt-get install -y python-numpy postgis postgresql-9.1 postgresql-client-9.1 postgresql-9.1-postgis-2.1 postgresql-9.1-postgis-2.1-scripts libpq-dev libpng12-dev libjpeg-dev libgif-dev liblzma-dev libgeos-dev libcurl4-gnutls-dev libproj-dev libxml2-dev libexpat-dev libxerces-c-dev libnetcdf-dev netcdf-bin libpoppler-dev libspatialite-dev gpsbabel swig libhdf4-alt-dev libhdf5-serial-dev libpodofo-dev poppler-utils libfreexl-dev unixodbc-dev libwebp-dev libepsilon-dev libgta-dev liblcms2-2 libpcre3-dev libcrypto++-dev
  - sudo i386 chroot "$chroot" apt-get install -y make
  - sudo i386 chroot "$chroot" apt-get install -y python-dev

# installing PostGIS 2 from Ubuntu PPA draws libgdal1.9 dependency. We must install ourselves
# in /usr too to avoid gdal version conflict. Might be fragile however

install:
  - sudo i386 chroot "$chroot" sh -c "cd $PWD/gdal && CC=clang CXX=clang ./configure --prefix=/usr --without-libtool --enable-debug --with-jpeg12 --with-python --with-poppler --with-podofo --with-spatialite --with-mysql --with-liblzma --with-webp --with-epsilon --with-gta"
  - sudo i386 chroot "$chroot" sh -c "cd $PWD/gdal && make USER_DEFS=-Werror -j3"
  - sudo i386 chroot "$chroot" sh -c "cd $PWD/gdal/apps && make USER_DEFS=-Werror -j3 test_ogrsf"
  - sudo i386 chroot "$chroot" sh -c "rm -f /usr/lib/libgdal.so*"
  - sudo i386 chroot "$chroot" sh -c "cd $PWD/gdal && make install"
  - sudo i386 chroot "$chroot" sh -c "sudo ldconfig"
  - sudo i386 chroot "$chroot" sh -c "cd autotest/cpp && make -j3"

script:
  - sudo i386 chroot "$chroot" sh -c "cd autotest/cpp && make quick_test"
# Compile and test vsipreload
  - sudo i386 chroot "$chroot" sh -c "cd autotest/cpp && make vsipreload.so"
# Run all the Python autotests
  - sudo i386 chroot "$chroot" sh -c "cd autotest && python run_all.py"

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true

