# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

language: cpp

compiler:
  - gcc

before_install:
  - cat /etc/apt/sources.list
  - ls -al /etc/apt/sources.list.d
  - sudo apt-get update -qq
  - sudo apt-get install binutils-mingw-w64-i686
  - sudo apt-get install gcc-mingw-w64-i686
  - sudo apt-get install g++-mingw-w64-i686
  - sudo apt-get install g++-mingw-w64
  - sudo apt-get install mingw-w64-tools
  - sudo apt-get install -y wine1.4-amd64
#  - psql -c "drop database if exists autotest" -U postgres
#  - psql -c "create database autotest" -U postgres
#  - psql -c "create extension postgis" -d autotest -U postgres
#  - mysql -e "create database autotest;"
#  - mysql -e "GRANT ALL ON autotest.* TO 'root'@'localhost';" -u root
#  - mysql -e "GRANT ALL ON autotest.* TO 'travis'@'localhost';" -u root

install:
  - wine64 cmd /c dir
  - ln -s /usr/lib/gcc/x86_64-w64-mingw32/4.6/libstdc++-6.dll  $HOME/.wine/drive_c/windows
  - ln -s /usr/lib/gcc/x86_64-w64-mingw32/4.6/libgcc_s_sjlj-1.dll  $HOME/.wine/drive_c/windows
# build proj
  - curl http://download.osgeo.org/proj/proj-4.9.2.tar.gz > proj-4.9.2.tar.gz
  - tar xvzf proj-4.9.2.tar.gz
  - cd proj-4.9.2/nad
  - curl http://download.osgeo.org/proj/proj-datumgrid-1.5.tar.gz > proj-datumgrid-1.5.tar.gz
  - tar xvzf proj-datumgrid-1.5.tar.gz
  - cd ..
  - CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ LD=x86_64-w64-mingw32-ld ./configure --host=x86_64-w64-mingw32
  - make -j3
  - cd ..
# build GDAL
  - cd gdal
  - CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ ./configure --enable-debug --host=x86_64-w64-mingw32
  - make USER_DEFS="-Wextra -Werror" -j3
  - cd apps
  - make USER_DEFS="-Wextra -Werror" test_ogrsf.exe
  - cd ..
  - ln -sf $PWD/.libs/libgdal-20.dll $HOME/.wine/drive_c/windows
  - ln -sf $PWD/../proj-4.9.2/src/.libs/libproj-9.dll $HOME/.wine/drive_c/windows
# Python bindings
  - wget http://www.python.org/ftp/python/2.7.3/python-2.7.3.amd64.msi
  - wine64 msiexec /i python-2.7.3.amd64.msi
  - cd swig/python
  - gendef $HOME/.wine/drive_c/Python27/python27.dll
  - x86_64-w64-mingw32-dlltool --dllname $HOME/.wine/drive_c/Python27/python27.dll --input-def python27.def --output-lib $HOME/.wine/drive_c/Python27/libs/libpython27.a
  - CXX=x86_64-w64-mingw32-g++ bash fallback_build_mingw32_under_unix.sh 
  - cd ../..

script:
  - wine64 apps/gdalinfo.exe --version
  - cd ../autotest
# Does not work under wine
  - rm gcore/gdal_api_proxy.py
  - rm gcore/rfc30.py
# Run all the Python autotests
  - GDAL_DATA=$PWD/../gdal/data PYTHONPATH=$PWD/../gdal/swig/python/build/lib.win-amd64-2.7 PATH=$PWD/../gdal:$PWD/../gdal/apps/.libs:$PWD:$PATH $HOME/.wine/drive_c/Python27/python.exe run_all.py

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true
    on_success: change
