# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

sudo: yes
dist: trusty

language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install qemu qemu-kvm
  - wget ftp://ftp.stacklet.com/archive/x86-64/FreeBSD/9.2/freebsd.9-2.x86-64.20140103.raw.img.txz
  - tar xJvf freebsd.9-2.x86-64.20140103.raw.img.txz
  - kvm -daemonize -display none freebsd.9-2.x86-64.20140103.raw.img -m 1536 -smp 4 -net user,hostfwd=tcp::10022-:22 -net nic
  - wget http://fossies.org/linux/privat/sshpass-1.06.tar.gz
  - tar xvzf sshpass-1.06.tar.gz
  - cd sshpass-1.06 && ./configure && make -j3 && cd ..
  - export MYSSH="sshpass-1.06/sshpass -p password ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost -p10022"
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg bootstrap'
  - $MYSSH 'mkdir /etc/pkg'
  - sshpass-1.06/sshpass -p password scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 10022 FreeBSD.conf root@localhost:/etc/pkg/FreeBSD.conf
  - $MYSSH 'cat /etc/pkg/FreeBSD.conf'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg update'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install gcc48'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install gmake'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install python27'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install py27-numpy'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install sqlite3 curl'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install expat'
  - $MYSSH 'wget https://github.com/OSGeo/gdal/archive/trunk.zip --no-check-certificate'
  - $MYSSH 'unzip trunk.zip'

install:
  - $MYSSH 'cd gdal-trunk/gdal && env CC=gcc48 env CXX=g++48 ./configure --enable-debug --without-libtool'
  - $MYSSH 'cd gdal-trunk/gdal && gmake -j4 -s USER_DEFS=-Werror'
  - $MYSSH 'cd gdal-trunk/gdal/apps && gmake -j4 -s USER_DEFS=-Werror test_ogrsf'
  - $MYSSH 'cd gdal-trunk/gdal && cd swig/python/ && env CC=gcc48 python2.7 setup.py build'

script:
  - $MYSSH 'cd gdal-trunk/autotest && env PYTHONPATH=$PWD/../gdal/swig/python/build/lib.freebsd-9.2-RELEASE-amd64-2.7 env LD_LIBRARY_PATH=$PWD/../gdal:/usr/local/lib/gcc48 env PATH=$PWD/../gdal/apps:$PATH env GDAL_DATA=$PWD/../gdal/data python2.7 run_all.py'

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true
    on_success: change
