# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org on a Mac-OSX machine

language: objective-c
osx_image: xcode8

# We use clang, --without-libtool and --with-debug for faster build
compiler:
  - clang

install:
# build proj
  - sudo brew uninstall gdal
  - curl http://download.osgeo.org/proj/proj-4.9.3.tar.gz > proj-4.9.3.tar.gz
  - tar xvzf proj-4.9.3.tar.gz
  - cd proj-4.9.3/nad
  - curl http://download.osgeo.org/proj/proj-datumgrid-1.5.tar.gz > proj-datumgrid-1.5.tar.gz
  - tar xvzf proj-datumgrid-1.5.tar.gz
  - cd ..
  - ./configure --prefix=$HOME/install-proj
  - make -j3
  - make install
  - cd ..
# build GDAL
  - cd gdal
  - ./configure --enable-debug --with-jpeg12 --with-python --with-geotiff=internal --with-png=internal --with-static-proj4=$HOME/install-proj
  - make USER_DEFS="-Wextra -Werror" -j3
  - cd apps
  - make USER_DEFS="-Wextra -Werror" test_ogrsf
  - cd ..
  - export PATH=$PWD/apps/.libs:$PWD/apps:$PATH
  - export DYLD_LIBRARY_PATH=$PWD/.libs
  - export GDAL_DATA=$PWD/data
  - export PYTHONPATH=$PWD/swig/python/build/lib.macosx-10.11-x86_64-2.7
  - cd ../autotest/cpp
  - echo $PATH
#  - sudo rm -rf /usr/local/Cellar/gdal/1.10.1_1/*
#  - sudo ln -s /usr/bin /usr/local/Cellar/gdal/1.10.1_1
#  - sudo ln -s /usr/lib /usr/local/Cellar/gdal/1.10.1_1
#  - sudo ln -s /usr/include /usr/local/Cellar/gdal/1.10.1_1
#  - sudo mkdir /usr/local/Cellar/gdal/1.10.1_1/share
#  - sudo ln -s /usr/share/gdal /usr/local/Cellar/gdal/1.10.1_1/share
  - gdal-config --version
  - gdal-config --cflags
  - make -j3
  - cd ../../gdal

script:
# CPP unit tests
  - cd ../autotest
  - cd cpp
  - GDAL_SKIP=JP2ECW make quick_test
  - cd ..
# Run all the Python autotests
#  - make -j test
  - python run_all.py

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true
    on_success: change
