# This is the config file for building GDAL with Travis-ci.org

language: cpp

compiler:
  - clang

before_install:
  - wget http://dl.google.com/android/ndk/android-ndk-r9d-linux-x86_64.tar.bz2
  - tar xjf android-ndk-r9d-linux-x86_64.tar.bz2
  - android-ndk-r9d/build/tools/make-standalone-toolchain.sh --platform=android-8 --install-dir=$HOME/android-8-toolchain

install:
  - cd gdal
  - unset CC
  - unset CXX
  - export PATH=$HOME/android-8-toolchain/bin:$PATH
  - CFLAGS="-mthumb" CXXFLAGS="-mthumb" LIBS="-lsupc++ -lstdc++" ./configure --host=arm-linux-androideabi
  - make USER_DEFS="-Wextra -Werror" -j3

script:
  - echo "finished"

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true

