# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

sudo: yes
dist: trusty

language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install linux-headers-`uname -r`
  - wget http://wiki.qemu.org/download/kqemu-1.4.0pre1.tar.gz
  - tar xzf kqemu-1.4.0pre1.tar.gz
  - cd kqemu-1.4.0pre1
  - patch -p0 < ../kqemu.patch
  - ./configure
  - make
  - sudo insmod kqemu.ko
  - sudo chmod a+rw /dev/kqemu
  - cd ..
#  - sudo apt-get install user-mode-linux
  #- sudo apt-get install qemu
# qemu-kvm
#  - kvm -daemonize -display none freebsd.9-2.x86-64.20140103.raw.img -m 1536 -smp 4 -net user,hostfwd=tcp::10022-:22 -net nic
  - wget https://download.savannah.gnu.org/releases/qemu/qemu-0.11.1.tar.gz
  - tar xzf qemu-0.11.1.tar.gz
  - cd qemu-0.11.1
  - patch -p0 < ../qemu.patch
  - ./configure --target-list=x86_64-softmmu --prefix=$PWD/../install-qemu --disable-kvm
  - make -j4
  - make -j4 install
  - cd ..
  - wget ftp://ftp.stacklet.com/archive/x86-64/FreeBSD/9.2/freebsd.9-2.x86-64.20140103.raw.img.txz
  - tar xJvf freebsd.9-2.x86-64.20140103.raw.img.txz
  - install-qemu/bin/qemu-system-x86_64 -enable-kqemu -daemonize -nographic freebsd.9-2.x86-64.20140103.raw.img -m 1536  -net user,hostfwd=tcp::10022-:22 -net nic,model=e1000 -parallel none
  #- qemu-system-x86_64 -daemonize -display none freebsd.9-2.x86-64.20140103.raw.img -m 1536 -smp 4 -net user,hostfwd=tcp::10022-:22 -net nic
  - wget http://fossies.org/linux/privat/sshpass-1.06.tar.gz
  - tar xzf sshpass-1.06.tar.gz
  - cd sshpass-1.06 && ./configure && make -j3 && cd ..
  - export MYSSH="sshpass-1.06/sshpass -p password ssh  -o ServerAliveInterval=30 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost -p10022"
  - sleep 60
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg bootstrap'
  - $MYSSH 'mkdir /etc/pkg'
  - sshpass-1.06/sshpass -p password scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 10022 FreeBSD.conf root@localhost:/etc/pkg/FreeBSD.conf
  - $MYSSH 'cat /etc/pkg/FreeBSD.conf'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg update'
#  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install gcc48'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install gmake'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install python27'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install py27-numpy'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install sqlite3 curl'
  - $MYSSH 'env ASSUME_ALWAYS_YES=YES pkg install expat'
  - $MYSSH 'curl -s -L https://github.com/OSGeo/gdal/archive/trunk.zip > trunk.zip'
  - $MYSSH 'unzip -q trunk.zip'

install:
  - $MYSSH 'cd gdal-trunk/gdal && env CC=gcc48 env CXX=g++48 ./configure --enable-debug --without-libtool'
  - $MYSSH 'cd gdal-trunk/gdal && gmake -j2 USER_DEFS=-Werror port-target core-target frmts-target ogr-target gnm-target appslib-target'
  - $MYSSH 'sync'
  - $MYSSH 'halt'
  - sleep 30
  - killall qemu-system-x86_64
  - export MYSSH="sshpass-1.06/sshpass -p password ssh  -o ServerAliveInterval=30 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost -p10023"
  - install-qemu/bin/qemu-system-x86_64 -daemonize -nographic freebsd.9-2.x86-64.20140103.raw.img -m 1536  -net user,hostfwd=tcp::10023-:22 -net nic,model=e1000 -parallel none
  - sleep 60
  - $MYSSH 'cd gdal-trunk/gdal && gmake lib-target USER_DEFS=-Werror'
  - $MYSSH 'sync'
  - $MYSSH 'halt'
  - sleep 30
  - killall qemu-system-x86_64
  - export MYSSH="sshpass-1.06/sshpass -p password ssh  -o ServerAliveInterval=30 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost -p10024"
  - install-qemu/bin/qemu-system-x86_64 -enable-kqemu -daemonize -nographic freebsd.9-2.x86-64.20140103.raw.img -m 1536  -net user,hostfwd=tcp::10024-:22 -net nic,model=e1000 -parallel none
  - sleep 30
  - $MYSSH 'cd gdal-trunk/gdal/apps && gmake -s USER_DEFS=-Werror'
  - $MYSSH 'cd gdal-trunk/gdal/apps && gmake -s USER_DEFS=-Werror test_ogrsf'
  - $MYSSH 'cd gdal-trunk/gdal && cd swig/python/ && env CC=gcc48 python2.7 setup.py build'

script:
  - $MYSSH 'cd gdal-trunk/autotest && env PYTHONPATH=$PWD/../gdal/swig/python/build/lib.freebsd-9.2-RELEASE-amd64-2.7 env LD_LIBRARY_PATH=$PWD/../gdal:/usr/local/lib/gcc48 env PATH=$PWD/../gdal/apps:$PATH env GDAL_DATA=$PWD/../gdal/data python2.7 run_all.py'

notifications:
  email:
    recipients:
      - gdal-commits@lists.osgeo.org

  irc:
    channels:
      - "irc.freenode.org#gdal"
    use_notice: true
    on_success: change
