platform:
- x86
- x64

shallow_clone: true

install:
- cd gdal
- SET PATH=c:\python27;%PATH%
- if "%platform%" == "x86" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
- if "%platform%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
- if "%platform%" == "x64" set WIN64_ARG="WIN64=YES"
- nmake /f makefile.vc MSVC_VER=1800 DEBUG=1 %WIN64_ARG%
- cd swig\python
- python setup.py build
- cd ..\..

build: off
test: off
test_script: off
deploy: off
