platform:
- x86

shallow_clone: true

install:
- cd gdal
- SET PATH=c:\python27;%PATH%
- call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
- nmake /f makefile.vc MSVC_VER=1800

build: off
test: off
test_script: pff
deploy: Ooff
