platform:
- x64
- x86

shallow_clone: true

install:
- cd gdal
- if "%platform%" == "x86" SET PATH=c:\python27;%PATH%
- if "%platform%" == "x64" SET PATH=c:\Python27-x64;%PATH%
- if "%platform%" == "x86" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
- if "%platform%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
- if "%platform%" == "x64" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
- if "%platform%" == "x64" set WIN64_ARG="WIN64=YES"
- nmake /f makefile.vc MSVC_VER=1800 DEBUG=1 %WIN64_ARG%
- cd apps
- nmake /f makefile.vc test_ogrsf.exe MSVC_VER=1800 DEBUG=1 %WIN64_ARG%
- cd ..
- cd swig\python
- python setup.py build
- python setup.py install
- cd ..\..
- cd ..\autotest\cpp
- nmake /f makefile.vc MSVC_VER=1800 %WIN64_ARG%
- cd ..\..


build_script:
  - echo build_script

test_script:
  - echo test_script
  - SET PATH=%CD%\gdal;%CD%\gdal\apps;%PATH%
  - SET GDAL_DATA=%CD%\gdal\data
  - cd autotest
  - python run_all.py

deploy: off

